# Generated by Django 5.1.3 on 2024-11-17 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('attendees', models.PositiveIntegerField(verbose_name='Number of Attendees')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venue_app.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Available Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='venue_app.venue')),
            ],
        ),
    ]
