# Generated by Django 5.1.3 on 2024-11-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_Attendee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_event_organizer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_venue_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('organizer', 'Event Organizer'), ('attendee', 'Attendee'), ('venue_manager', 'Venue Manager')], default='attendee', max_length=20),
        ),
    ]
