# Generated by Django 5.1.3 on 2024-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming')], default='upcoming', max_length=50),
        ),
    ]
